apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qhhpdbsa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/go-qhhpdbsa:ceae16af27b3292be9dbcec448940fdc59e1df79@sha256:d01cae96d6972999fe972f65ccef9c8aef5787051088c5aaef88b703636ba0d1
          name: container-image
